### ISSUE TITLE
magit-dispatch-popup configuration

### ISSUE THREAD

**Issue by andreyorst** [justbur/emacs-vdiff-magit#4]
Hello, today I've installed vdiff-magit from Melpa, and I'm having troubles with setting `vdiff-magit`.

I've used your sample configuration from the README (adopted for use-package):
```emacs-lisp
(use-package vdiff-magit
    :after (magit vdiff)
    :bind (:map magit-mode-map
                ("e" . vdiff-magit-dwim)
                ("E" . vdiff-magit-popup))
    :config
    (setcdr (assoc ?e (plist-get magit-dispatch-popup :actions))
            '("vdiff dwim" 'vdiff-magit-dwim))
    (setcdr (assoc ?E (plist-get magit-dispatch-popup :actions))
            '("vdiff popup" 'vdiff-magit-popup)))
```
And got this error:
```
Error (use-package): vdiff-magit/:config: Symbol’s value as variable is void: magit-dispatch-popup
```

I've tried to configure it without `use-package`, but got the same error:
```
Symbol's value as variable is void: magit-dispatch-popup
```
So I'm assuming it is not a problem with `use-package`

Looking through the [Magit release notes](https://github.com/magit/magit/blob/master/Documentation/RelNotes/2.91.0.org), I see that:
> `magit-dispatch-popup` has been renamed to `magit-dispatch` and continues to be available on h, ? and C-c C-c. #3659

However using `magit-dispatch` instead of `magit-dispatch-popup` in the configuration snippet doesn't work too.

When I manually call `vdiff-magit-popup`, I can see the popup, but I get `*Warnings*` buffer opened, with an error message of `Symbol’s value as variable is void: magit-dispatch(-popup)`

**Comment by justbur** [comment]
Please see the updates in the readme. If that doesn't work for you, let me know.

**Comment by andreyorst** [comment]
It works fine now. Thanks!
