### ISSUE TITLE
Magit-Popup dependency

### ISSUE THREAD

**Issue by andreyorst** [justbur/emacs-vdiff-magit#5]
I've updated magit, and got this warning when tried to call `vdiff-magit-popup`:

> Warning (magit): Magit no longer uses Magit-Popup.
> It now uses Transient.
> See https://emacsair.me/2019/02/14/transient-0.1.
> 
> However your configuration and/or some third-party package that
> you use still depends on the `magit-popup' package.  But because
> `magit' no longer depends on that, `package' has removed it from
> your system.
> 
> If some package that you use still depends on `magit-popup' but
> does not declare it as a dependency, then please contact its
> maintainer about that and install `magit-popup' explicitly.
> 
> If you yourself use functions that are defined in `magit-popup'
> in your configuration, then the next step depends on what you use
> that for.
> 
> * If you use `magit-popup' to define your own popups but do not
>   modify any of Magit's old popups, then you have to install
>   `magit-popup' explicitly.  (You can also migrate to Transient,
>   but there is no need to rush that.)
> 
> * If you add additional arguments and/or actions to Magit's popups,
>   then you have to port that to modify the new "transients" instead.
>   See https://github.com/magit/magit/wiki/Converting-popup-modifications-to-transient-modifications
>

**Comment by justbur** [comment]
Thanks. It should work with b4a0407
